### PR TITLE
new team member omer added

### PR DESCRIPTION
**Pull request by lawyer-omer**

### CODE REVIEW

**Comment by tayfunoziserikan** [comment]
@lawyer-omer  First of all, thank you for the PR. Can you change your title to "Intern Candidate" [at this line](https://github.com/lab2023/lab2023.com/pull/94/commits/ed5f6f6669ddf778feedc3de2fefb83daa84c118#diff-f41ccf78e14181f6d5fc7ec5a66d55b387b3573f7518ce7124c383dc6317630aR95) for now? I will consider this PR once our trial period ends and If we have decided to work with you.
Best wishes.

**Comment by daniel-legaltech** [comment]
Thank you for the brief explanation. But, could you please
explain more about what is different between intern and intern
candidates for your side?  As far as I know, I'm an intern which
is in the trial period, and we will discuss the full-time
employment stage at the end of this period. Am I wrong about
this?

Best,
Omer

--

**Comment by tayfunoziserikan** [comment]
> Thank you for the brief explanation. But, could you please explain more about what is different between intern and intern candidates for your side?  As far as I know, I'm an intern which is in the trial period, and we will discuss the full-time employment stage at the end of this period. Am I wrong about this? Best, Omer
> […](#)

Yes, the words may be confusing. We will consider the full-time recruitment process if we decide to work after the trial. Currently, you're a candidate for us.

**Comment by daniel-legaltech** [comment]
Got it, thanks!

Ps: I've fixed the title.

--



On September 23, 2022 at 1:44 PM, Tayfun (Öziş) Erikan
***@***.***) wrote:
>> Thank you for the brief explanation. But, could you please
>> explain more about what is different between intern and intern
>> candidates for your side?  As far as I know, I'm an intern which
>> is in the trial period, and we will discuss the full-time
>> employment stage at the end of this period. Am I wrong about
>> this? Best, Omer
>> … <http://#>
Yes, the words may be confusing. We will consider the full-time

**Pull request closed without merging**
