### PR TITLE
LMC-14 #time 3h - Blog was written about what is Fineuploader and how…

### PR DESCRIPTION
**Pull request by hamdibayhan**
… to use Fineuploader

### CODE REVIEW

**Comment by rnicholus** [comment]
Thanks for the mention. Nice article!

**Comment by hamdibayhan** [comment]
@rnicholus We like Fineuploader as a Rails user, but I don't understand why does not the Rails logo look in the following logos found on the main page of Fineuploader?
fineuploader

**Comment by rnicholus** [comment]
Simple: no one has contributed a server side example for Rails to the GitHub org, thats why.

**Comment by hamdibayhan** [comment]
@rnicholus  You are wrong, there is react fineuploder example with Rails in [here](https://github.com/FineUploader/react-fine-uploader-rails) made by @Panczo . I think this example is enough for Rails logo. We are also thinking about creating an example with Rails for fineuploader. If we make the example, we'll inform you.

**Comment by rnicholus** [comment]
I stand corrected. Guess I forgot about that repo. If you are able to contribute an updated image that contains the Rails logo, I'd be happy to make it live. The image is at https://github.com/FineUploader/fineuploader.com/blob/gh-pages/img/server-support.png.

**Comment by hamdibayhan** [comment]
@rnicholus  I will contribute for this issue as soon as possible. As I say, we like fineuploader. :)

**Pull request merged**
